/*
 * This source file was generated by the Gradle 'init' task
 */
package org.fileManagement.utilities;

import org.mindrot.jbcrypt.BCrypt;

public class AuthUtils {
    public static String hashPassword(String password) {
        return BCrypt.hashpw(password, BCrypt.gensalt());
    }

    public static boolean verifyPassword(String password, String hashedPassword) {
        return BCrypt.checkpw(password, hashedPassword);
    }
}
