/*
 * This source file was generated by the Gradle 'init' task
 */
package org.fileManagement.app;

public class App {
    public static User currentUser = null;

    public static void main(String[] args) {
        Command.handleCommand(currentUser);
    }
}
